# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Second item
    path: entry/1
    submenu:
      - label: Sub 1
        path: entry/2
      - label: Sub 2
        class: menu-item-class
        path: entry/3
      - label: Sub 3
        path: entry/4
      - label: Sub 4
        class: sub-class
        path: page/3
  - label: All pages
    path: pages/
  - label: The Bolt site
    link: http://bolt.cm
    class: last

# this is the site-map
sitemap:
  - label: Connect
    path: connect
    submenu:
      - label: "Time & Location"
        path: "connect#time"
      - label: What We Believe
        path: "connect#believe"
      - label: Worship
        path: "connect#worship"
      - label: Staff
        path: "connect#staff"
  - label: Grow
    path: grow
    submenu:
      - label: "Life Stage"
        path: "grow#life-stage"
      - label: "Faith @ Home"
        path: "grow#faith-at-home"
      - label: Ways We Serve
        path: "grow#ways-we-serve"
      - label: Volunteer
        path: "grow#volunteer"
      - label: Give
        path: "grow#give"
      - label: Learning
        path: "grow#learning"
  - label: Resources
    path: resources
    submenu:
      - label: Special Series
        path: "resources#special-series"
      - label: "Making Room"
        path: "resources#making-room"
      - label: "English Conversations"
        path: "resources#english-conversations"
      - label: "Praise Press"
        path: "resources#praise-press"
      - label: "Calendar"
        path: "resources#calendar"
