# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Second item
    path: entry/1
    submenu:
      - label: Sub 1
        path: entry/2
      - label: Sub 2
        class: menu-item-class
        path: entry/3
      - label: Sub 3
        path: entry/4
      - label: Sub 4
        class: sub-class
        path: page/3
  - label: All pages
    path: pages/
  - label: The Bolt site
    link: http://bolt.cm
    class: last

# this is the site-map
sitemap:
  - label: Connect
    path: page/connect
    submenu:
      - label: "Time & Location"
        path: "page/connect#time"
      - label: What We Believe
        path: "page/connect#believe"
      - label: Worship
        path: "page/connect#worship"
      - label: Staff
        path: "page/connect#staff"
  - label: Grow
    path: page/grow
    submenu:
      - label: "Life Stage"
        path: "page/grow#life-stage"
      - label: "Faith @ Home"
        path: "page/grow#faith-at-home"
      - label: Ways We Serve
        path: "page/grow#ways-we-serve"
      - label: Volunteer
        path: "page/grow#volunteer"
      - label: Give
        path: "page/grow#give"
      - label: Learning
        path: "page/grow#learning"
  - label: Resources
    path: page/resources
    submenu:
      - label: Special Series
        path: "page/resources#special-series"
      - label: "Making Room"
        path: "page/resources#making-room"
      - label: "English Conversations"
        path: "page/resources#english-conversations"
      - label: "Praise Press"
        path: "page/resources#praise-press"
      - label: "Calendar"
        path: "page/resources#calendar"
