# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus
sitemap:
  - label: Connect
    path: page/connect
    submenu:
      - label: "Time & Location"
        path: "page/connect#time"
      - label: What We Believe
        path: "page/connect#believe"
      - label: Worship [m]
        path: "page/connect#worship"
      - label: Staff
        path: "page/connect#staff"
  - label: Grow
    path: page/grow
    submenu:
      - label: "Life Stage"
        path: "page/life-stage"
      - label: "Faith @ Home"
        path: "page/faith-at-home"
      - label: Ways We Serve
        path: "page/ways-we-serve"
      - label: Volunteer [m]
        path: "page/volunteer"
      - label: Give
        path: "http://donate.mattisave.org"
      - label: Learning [m]
        path: "page/learning"
  - label: Resources
    path: page/resources
    submenu:
      - label: Special Series
        path: "page/resources#special-series"
      - label: "Making Room"
        path: "page/resources#making-room"
      - label: "English Conversations"
        path: "page/resources#english-conversations"
      - label: "Praise Press"
        path: "page/resources#praise-press"
      - label: "Calendar"
        path: "page/resources#calendar"
